/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calificaciones;
import java.util.*;
import java.io.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author luisa
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        llenarTabla();
    }
    
    private void llenarTabla() {
        List<String[]> filas=new ArrayList<>();
        int columnas=0;

        try (BufferedReader scan=new BufferedReader(new FileReader("src/Archivos/materias.txt"))) {
            String linea;
            while((linea=scan.readLine())!=null) {
                String[] arr=linea.split(",");
                filas.add(arr);
                int unidades=arr.length-1;
                if(unidades>columnas) {
                    columnas=unidades;
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Archivo de materias corrupto");
            return;
        }

        String[] NumUnidad=new String[1+columnas];
        NumUnidad[0]= "Materia";
        for(int i=1;i<=columnas;i++) {
            NumUnidad[i]="Unidad "+i;
        }
        
        DefaultTableModel base=new DefaultTableModel(NumUnidad,0);

        for(String[] ArrFilas:filas) {
            String[] filaCompleta=new String[1+columnas];
            Arrays.fill(filaCompleta,"");

            for(int i=0;i<ArrFilas.length;i++) {
                filaCompleta[i]=ArrFilas[i];
            }
            base.addRow(filaCompleta);
        }
        tbMaterias.setModel(base);
        tbMateriasEdit.setModel(base);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMaterias = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMateriasEdit = new javax.swing.JTable();
        btnAnadirCaptura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbMaterias);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Captura de Caliicaciones", jPanel1);

        tbMateriasEdit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbMateriasEdit);

        btnAnadirCaptura.setText("Añadir captura");
        btnAnadirCaptura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirCapturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAnadirCaptura)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAnadirCaptura)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Captura de Calificaciones", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirCapturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirCapturaActionPerformed
        String nombreAlumno=JOptionPane.showInputDialog(this,"Alumno:");
        String nombreMateria=JOptionPane.showInputDialog(this,"Materia:");
        String numUnidad=JOptionPane.showInputDialog(this,"Unidad:");
        String calificacion=JOptionPane.showInputDialog(this,"Calificación:");
        
        
        
        try {
            int unidad=Integer.parseInt(numUnidad);
            DefaultTableModel base=(DefaultTableModel)tbMateriasEdit.getModel();

            boolean materiaNueva=false;
            for(int i=0;i<base.getRowCount();i++) {
                if(base.getValueAt(i,0).equals(nombreMateria)) {
                    if(unidad>=base.getColumnCount()) {
                        while(base.getColumnCount()<=unidad) {
                            base.addColumn("Unidad "+base.getColumnCount());
                        }
                    }
                    base.setValueAt(String.valueOf(calificacion),i,unidad);
                    materiaNueva=true;
                    break;
                }
            }
            if(!materiaNueva) {
                int columna=base.getColumnCount();
                String[] nuevaFila=new String[columna];
                Arrays.fill(nuevaFila,"");
                nuevaFila[0]=nombreMateria;
                if(unidad<columna) {
                    nuevaFila[unidad]=String.valueOf(calificacion);
                } else {
                    while(base.getColumnCount()<=unidad) {
                        base.addColumn("Unidad "+base.getColumnCount());
                    }
                    nuevaFila=Arrays.copyOf(nuevaFila,base.getColumnCount());
                    nuevaFila[unidad]=String.valueOf(calificacion);
                }
                base.addRow(nuevaFila);

                //guardar en archivo
                try(BufferedWriter escrito=new BufferedWriter(new FileWriter("src/Archivos/materias.txt", true))) {
                    StringBuilder linea=new StringBuilder(nombreMateria);
                    for(int i=1;i<nuevaFila.length;i++) {
                        if(!nuevaFila[i].isEmpty()) {
                            linea.append(",").append(nuevaFila[i]);
                        }
                    }
                    escrito.newLine();
                    escrito.write(linea.toString());
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Archivo de materias corrupto");
                }
            }

        } 
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Datos invalidos");
        }
    }//GEN-LAST:event_btnAnadirCapturaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadirCaptura;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbMaterias;
    private javax.swing.JTable tbMateriasEdit;
    // End of variables declaration//GEN-END:variables
}
